[package]
name = "tasktrack-core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio"] }
tokio = { version = "1.45.1", features = ["full"] }
