//! Shell integration: `cd task`, `cd code [name]`, `cd build [name]`.
//!
//! pahiri never edits the user's dotfiles. For zsh it points `ZDOTDIR` at a
//! generated directory whose startup files source the user's own files and
//! then define a `cd` wrapper; for bash it passes `--rcfile`. The wrapper
//! reads a small per-task env file on every call, so attaching a workspace
//! takes effect in shells that are already open.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Environment and arguments to launch a shell with integration enabled.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ShellLaunch {
    /// Extra environment variables.
    pub env: Vec<(String, String)>,
    /// The complete argument list (integration flags plus the user's own).
    pub args: Vec<String>,
}

const POSIX_FUNCTIONS: &str = r#"
__pahiri_load() {
  if [ -n "$PAHIRI_ENV_FILE" ] && [ -r "$PAHIRI_ENV_FILE" ]; then . "$PAHIRI_ENV_FILE"; fi
}
__pahiri_cd_named() {
  # $1 = kind (code|build), $2 = list "name=path;name=path", $3 = default path, $4 = requested name
  if [ -z "$4" ]; then
    if [ -z "$3" ]; then
      echo "pahiri: no $1 attached to task ${PAHIRI_TASK:-?} (Esc, then a to attach)" >&2
      return 1
    fi
    builtin cd "$3" || return
    return
  fi
  __pahiri_entry=""
  __pahiri_old_ifs="$IFS"; IFS=';'
  for __pahiri_entry in $2; do
    case "$__pahiri_entry" in
      "$4="*) IFS="$__pahiri_old_ifs"; builtin cd "${__pahiri_entry#*=}" || return; return ;;
    esac
  done
  IFS="$__pahiri_old_ifs"
  echo "pahiri: no $1 named '$4' attached (have: $2)" >&2
  return 1
}
cd() {
  __pahiri_load
  case "$1" in
    task)
      if [ -z "$PAHIRI_TASK_DIR" ]; then echo "pahiri: no task" >&2; return 1; fi
      builtin cd "$PAHIRI_TASK_DIR" ;;
    code)  __pahiri_cd_named code "$PAHIRI_CODE_DIRS" "$PAHIRI_CODE_DIR" "$2" ;;
    build) __pahiri_cd_named build "$PAHIRI_BUILD_DIRS" "$PAHIRI_BUILD_DIR" "$2" ;;
    *) builtin cd "$@" ;;
  esac
}
"#;

fn zsh_wrapper(name: &str, orig_dir_var: &str) -> String {
    format!(
        "# generated by pahiri — sources your own {name} first\n\
         if [ -f \"${orig_dir_var}/{name}\" ]; then source \"${orig_dir_var}/{name}\"; fi\n"
    )
}

/// Prepare integration files for `program` under `state_dir`.
///
/// Returns the environment and argument additions; unknown shells get only
/// the environment (so `$PAHIRI_*` is still available).
pub fn prepare(state_dir: &Path, program: &str, user_args: &[String]) -> io::Result<ShellLaunch> {
    let shell_name = Path::new(program)
        .file_name()
        .map_or_else(|| program.to_owned(), |n| n.to_string_lossy().into_owned());
    let mut launch = ShellLaunch {
        env: Vec::new(),
        args: user_args.to_vec(),
    };
    match shell_name.as_str() {
        "zsh" => {
            let dir = state_dir.join("shell").join("zsh");
            fs::create_dir_all(&dir)?;
            let orig = std::env::var("ZDOTDIR")
                .ok()
                .filter(|s| !s.is_empty())
                .or_else(|| std::env::var("HOME").ok())
                .unwrap_or_else(|| "~".to_owned());
            for name in [".zshenv", ".zprofile", ".zlogin"] {
                fs::write(dir.join(name), zsh_wrapper(name, "PAHIRI_ORIG_ZDOTDIR"))?;
            }
            let mut zshrc = zsh_wrapper(".zshrc", "PAHIRI_ORIG_ZDOTDIR");
            zshrc.push_str(POSIX_FUNCTIONS);
            fs::write(dir.join(".zshrc"), zshrc)?;
            launch
                .env
                .push(("ZDOTDIR".into(), dir.display().to_string()));
            launch.env.push(("PAHIRI_ORIG_ZDOTDIR".into(), orig));
        }
        "bash" => {
            let dir = state_dir.join("shell").join("bash");
            fs::create_dir_all(&dir)?;
            // `--norc` means "not my ~/.bashrc": honour that but keep the wrapper.
            let norc = user_args.iter().any(|a| a == "--norc");
            let has_rcfile = user_args
                .iter()
                .any(|a| a == "--rcfile" || a == "--init-file");
            let mut rc = String::from("# generated by pahiri\n");
            if !norc {
                rc.push_str("if [ -f \"$HOME/.bashrc\" ]; then . \"$HOME/.bashrc\"; fi\n");
            }
            rc.push_str(POSIX_FUNCTIONS);
            let rc_path = dir.join(if norc { "bashrc-norc" } else { "bashrc" });
            fs::write(&rc_path, rc)?;
            if !has_rcfile {
                launch.args = vec!["--rcfile".into(), rc_path.display().to_string()];
                launch
                    .args
                    .extend(user_args.iter().filter(|a| *a != "--norc").cloned());
            }
        }
        _ => {}
    }
    Ok(launch)
}

/// Contents of a per-task env file consumed by the `cd` wrapper.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct TaskEnv {
    /// Task id.
    pub task: String,
    /// Task folder.
    pub task_dir: PathBuf,
    /// Attached code workspaces (name, path) in attachment order.
    pub code: Vec<(String, PathBuf)>,
    /// Attached builds (name, path) in attachment order.
    pub builds: Vec<(String, PathBuf)>,
}

fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

fn joined(items: &[(String, PathBuf)]) -> String {
    items
        .iter()
        .map(|(n, p)| format!("{n}={}", p.display()))
        .collect::<Vec<_>>()
        .join(";")
}

impl TaskEnv {
    /// Render the env file (plain POSIX assignments, safe to `.` in any shell).
    pub fn render(&self) -> String {
        let mut out = String::from("# generated by pahiri; sourced by the cd wrapper\n");
        let mut push = |k: &str, v: &str| {
            out.push_str(k);
            out.push('=');
            out.push_str(&sh_quote(v));
            out.push('\n');
        };
        push("PAHIRI_TASK", &self.task);
        push("PAHIRI_TASK_DIR", &self.task_dir.display().to_string());
        push(
            "PAHIRI_CODE_DIR",
            &self
                .code
                .first()
                .map(|(_, p)| p.display().to_string())
                .unwrap_or_default(),
        );
        push("PAHIRI_CODE_DIRS", &joined(&self.code));
        push(
            "PAHIRI_BUILD_DIR",
            &self
                .builds
                .first()
                .map(|(_, p)| p.display().to_string())
                .unwrap_or_default(),
        );
        push("PAHIRI_BUILD_DIRS", &joined(&self.builds));
        out
    }

    /// Variables to export into new shells (same values as the env file).
    pub fn exports(&self) -> Vec<(String, String)> {
        vec![
            ("PAHIRI_TASK".into(), self.task.clone()),
            (
                "PAHIRI_TASK_DIR".into(),
                self.task_dir.display().to_string(),
            ),
            (
                "PAHIRI_CODE_DIR".into(),
                self.code
                    .first()
                    .map(|(_, p)| p.display().to_string())
                    .unwrap_or_default(),
            ),
            ("PAHIRI_CODE_DIRS".into(), joined(&self.code)),
            (
                "PAHIRI_BUILD_DIR".into(),
                self.builds
                    .first()
                    .map(|(_, p)| p.display().to_string())
                    .unwrap_or_default(),
            ),
            ("PAHIRI_BUILD_DIRS".into(), joined(&self.builds)),
        ]
    }

    /// Write the env file for this task under `state_dir`, returning its path.
    pub fn write(&self, state_dir: &Path) -> io::Result<PathBuf> {
        let dir = state_dir.join("tasks");
        fs::create_dir_all(&dir)?;
        let path = dir.join(format!("{}.env", self.task));
        fs::write(&path, self.render())?;
        Ok(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    fn env(dir: &Path) -> TaskEnv {
        TaskEnv {
            task: "T-1".into(),
            task_dir: dir.join("tasks/T-1"),
            code: vec![
                ("fw".into(), dir.join("fw")),
                ("app".into(), dir.join("app")),
            ],
            builds: vec![("yocto".into(), dir.join("yocto"))],
        }
    }

    #[test]
    fn env_file_quotes_values() {
        let e = TaskEnv {
            task: "it's".into(),
            ..TaskEnv::default()
        };
        assert!(e.render().contains("PAHIRI_TASK='it'\\''s'\n"));
    }

    #[test]
    fn cd_wrapper_works_in_bash() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        for d in ["tasks/T-1", "fw", "app", "yocto"] {
            fs::create_dir_all(root.join(d)).unwrap();
        }
        let env_file = env(root).write(root).unwrap();
        let launch = prepare(root, "bash", &[]).unwrap();
        assert_eq!(launch.args[0], "--rcfile");
        let rc = &launch.args[1];
        let script = "cd task && pwd; cd code && pwd; cd code app && pwd; cd build && pwd; cd build nope; echo rc=$?; cd / && pwd";
        let out = Command::new("bash")
            .args(["--rcfile", rc, "-i", "-c", script])
            .env("HOME", root)
            .env("PAHIRI_ENV_FILE", &env_file)
            .output()
            .unwrap();
        let stdout = String::from_utf8_lossy(&out.stdout);
        let stderr = String::from_utf8_lossy(&out.stderr);
        let canon = |p: &str| {
            fs::canonicalize(root.join(p))
                .unwrap()
                .display()
                .to_string()
        };
        let lines: Vec<&str> = stdout.lines().collect();
        assert_eq!(lines[0], canon("tasks/T-1"), "{stdout}\n{stderr}");
        assert_eq!(lines[1], canon("fw"));
        assert_eq!(lines[2], canon("app"));
        assert_eq!(lines[3], canon("yocto"));
        assert_eq!(lines[4], "rc=1");
        assert_eq!(lines[5], "/");
        assert!(stderr.contains("no build named 'nope'"));
    }

    #[test]
    fn zsh_files_are_generated_and_other_shells_get_nothing() {
        let tmp = tempfile::tempdir().unwrap();
        let launch = prepare(tmp.path(), "/usr/bin/zsh", &[]).unwrap();
        assert!(launch.env.iter().any(|(k, _)| k == "ZDOTDIR"));
        let zdot = tmp.path().join("shell/zsh");
        for f in [".zshenv", ".zprofile", ".zshrc", ".zlogin"] {
            assert!(zdot.join(f).is_file(), "{f}");
        }
        assert!(fs::read_to_string(zdot.join(".zshrc"))
            .unwrap()
            .contains("cd() {"));
        let fish = prepare(tmp.path(), "fish", &["-l".into()]).unwrap();
        assert_eq!(
            fish,
            ShellLaunch {
                env: Vec::new(),
                args: vec!["-l".into()]
            }
        );
        let norc = prepare(tmp.path(), "bash", &["--norc".into(), "-i".into()]).unwrap();
        assert_eq!(norc.args[0], "--rcfile");
        assert!(norc.args[1].ends_with("bashrc-norc"));
        assert_eq!(norc.args[2..], ["-i".to_owned()]);
        assert!(!fs::read_to_string(&norc.args[1])
            .unwrap()
            .contains(".bashrc\""));
        let own = prepare(tmp.path(), "bash", &["--rcfile".into(), "/x".into()]).unwrap();
        assert_eq!(own.args, vec!["--rcfile".to_owned(), "/x".to_owned()]);
    }
}
