//! Per-task working state: file tree, shells, editor, focus and metadata.

use std::io;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use crate::config::Config;
use crate::editor::Buffer;
use crate::files::FileTree;
use crate::highlight::{Language, State};
use crate::tasks::context::{read_meta, write_meta};
use crate::tasks::{checkpoints, Checkpoint, TaskMeta, TaskSummary};
use crate::terminal::shellrc::{self, TaskEnv};
use crate::terminal::{PtySession, ShellId, SpawnOptions};

use super::event::{AppEvent, EventSender};

/// Which pane receives keys inside a task.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Focus {
    /// The file tree (top-left).
    Tree,
    /// The shell list (bottom-left).
    Shells,
    /// The document editor (top-right).
    Editor,
    /// The embedded terminal (bottom-right).
    Terminal,
}

/// A shell belonging to a task.
#[derive(Debug)]
pub struct Shell {
    /// The PTY session.
    pub session: PtySession,
    /// Sequence number within the task (1-based, for display).
    pub number: usize,
    /// tmux session backing this shell (when `shell.tmux` is on).
    pub tmux: Option<String>,
}

/// tmux socket name (`-L`) for pahiri's sessions.
pub fn tmux_socket() -> String {
    std::env::var("PAHIRI_TMUX_SOCKET").unwrap_or_else(|_| "pahiri".into())
}

/// A tmux session name for shell `n` of `task`.
pub fn tmux_session_name(task: &str, n: usize) -> String {
    let safe: String = task
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("pahiri-{safe}-{n}")
}

/// Kill a pahiri tmux session (ignores errors: it may be gone already).
pub fn kill_tmux_session(name: &str) {
    let _ = std::process::Command::new("tmux")
        .args(["-L", &tmux_socket(), "kill-session", "-t", name])
        .output();
}

/// Detach pahiri's client from a tmux session (the session keeps running).
///
/// Needed before a shell is dropped: dropping the PTY writer sends `^D`,
/// which a still-attached client would forward to the shell.
pub fn detach_tmux_session(name: &str) {
    let _ = std::process::Command::new("tmux")
        .args(["-L", &tmux_socket(), "detach-client", "-s", name])
        .output();
}

const TMUX_CONF: &str = "\
# generated by pahiri: tmux only keeps shells alive; pahiri draws the UI
set -g prefix None
unbind C-b
set -g status off
set -g mouse on
set -g escape-time 0
set -g history-limit 50000
set -g default-terminal \"xterm-256color\"
";

impl Shell {
    /// Display name: `zsh #2` or the window title when the program set one.
    pub fn display_name(&self) -> String {
        let base = format!("{} #{}", self.session.label(), self.number);
        match self.session.title() {
            Some(t) if !t.is_empty() => format!("{base} · {t}"),
            _ => base,
        }
    }
}

/// Cached highlight states for the open document.
#[derive(Debug, Clone)]
pub struct HighlightCache {
    /// Document the cache belongs to.
    pub path: PathBuf,
    /// Buffer revision the states were computed for.
    pub revision: u64,
    /// Detected language.
    pub language: Language,
    /// State before each line (see [`Language::line_states`]).
    pub states: Vec<State>,
}

/// Everything pahiri remembers about an opened task while it runs.
#[derive(Debug)]
pub struct TaskContext {
    /// Task id (folder name).
    pub id: String,
    /// Task folder.
    pub dir: PathBuf,
    /// Path of the context file.
    pub context_path: PathBuf,
    /// Metadata from the context file's managed block.
    pub meta: TaskMeta,
    /// File tree over the task folder.
    pub tree: FileTree,
    /// Shells opened for this task.
    pub shells: Vec<Shell>,
    /// Index of the selected shell.
    pub selected_shell: usize,
    /// The one open document, if any.
    pub editor: Option<Buffer>,
    /// Focused pane.
    pub focus: Focus,
    /// Whether the terminal pane is shown (when there are shells).
    pub show_shell: bool,
    /// Whether the terminal is zoomed to the whole screen.
    pub zoomed: bool,
    /// Per-task env file consumed by the `cd` wrapper.
    pub env_file: Option<PathBuf>,
    /// Highlight cache for the open document.
    pub highlight: Option<HighlightCache>,
    /// Checkpoints from the context file.
    pub checkpoints: Vec<Checkpoint>,
    /// Modification time of the context file when it was last read.
    context_mtime: Option<SystemTime>,
    next_number: usize,
}

fn mtime(path: &Path) -> Option<SystemTime> {
    std::fs::metadata(path).and_then(|m| m.modified()).ok()
}

impl TaskContext {
    /// Build the context for a task folder.
    pub fn new(summary: &TaskSummary, context_path: &Path, show_hidden: bool) -> io::Result<Self> {
        let tree = FileTree::new(&summary.dir, show_hidden)?;
        let meta = read_meta(context_path)?;
        let checkpoints = checkpoints::read(context_path)?;
        Ok(Self {
            id: summary.id.clone(),
            dir: summary.dir.clone(),
            context_path: context_path.to_path_buf(),
            meta,
            tree,
            shells: Vec::new(),
            selected_shell: 0,
            editor: None,
            focus: Focus::Tree,
            show_shell: true,
            zoomed: false,
            env_file: None,
            highlight: None,
            checkpoints,
            context_mtime: mtime(context_path),
            next_number: 1,
        })
    }

    /// Re-read metadata and checkpoints from the context file.
    pub fn reload_meta(&mut self) -> io::Result<()> {
        self.context_mtime = mtime(&self.context_path);
        self.meta = read_meta(&self.context_path)?;
        self.checkpoints = checkpoints::read(&self.context_path)?;
        Ok(())
    }

    /// Whether the context file changed since it was last read.
    pub fn context_changed_on_disk(&self) -> bool {
        mtime(&self.context_path) != self.context_mtime
    }

    /// Persist metadata into the context file.
    pub fn save_meta(&mut self) -> io::Result<()> {
        write_meta(&self.context_path, &self.id, &self.meta)?;
        self.context_mtime = mtime(&self.context_path);
        Ok(())
    }

    /// Environment describing this task for shells.
    pub fn task_env(&self, config: &Config) -> TaskEnv {
        TaskEnv {
            task: self.id.clone(),
            task_dir: self.dir.clone(),
            code: self
                .meta
                .workspaces
                .iter()
                .filter_map(|n| {
                    config
                        .workspace(n)
                        .map(|w| (w.name.clone(), w.path.clone()))
                })
                .collect(),
            builds: self
                .meta
                .builds
                .iter()
                .filter_map(|n| config.build(n).map(|b| (b.name.clone(), b.path.clone())))
                .collect(),
        }
    }

    /// Rewrite the env file so open shells see the current attachments.
    pub fn refresh_env(&mut self, config: &Config, state_dir: &Path) -> io::Result<()> {
        self.env_file = Some(self.task_env(config).write(state_dir)?);
        Ok(())
    }

    /// Launch a shell in the task folder and focus it.
    ///
    /// `cwd` defaults to the task folder. With `shell.tmux` the shell runs in
    /// tmux session `tmux` (a new name when `None`), created or reattached.
    pub fn spawn_shell(
        &mut self,
        id: ShellId,
        config: &Config,
        state_dir: &Path,
        events: EventSender,
        cwd: Option<PathBuf>,
        tmux: Option<String>,
    ) -> anyhow::Result<()> {
        if self.env_file.is_none() {
            self.refresh_env(config, state_dir)?;
        }
        let launch = shellrc::prepare(state_dir, &config.shell.program, &config.shell.args)?;
        let mut env = self.task_env(config).exports();
        env.push(("PAHIRI".into(), env!("CARGO_PKG_VERSION").into()));
        if let Some(f) = &self.env_file {
            env.push(("PAHIRI_ENV_FILE".into(), f.display().to_string()));
        }
        env.extend(launch.env);
        let cwd = cwd.unwrap_or_else(|| self.dir.clone());
        let number = self.next_number;
        let label = std::path::Path::new(&config.shell.program)
            .file_name()
            .map(|n| n.to_string_lossy().into_owned());
        let (program, args, tmux) = if config.shell.tmux {
            let name = tmux.unwrap_or_else(|| {
                // Skip names still running from an earlier session.
                let mut n = number;
                loop {
                    let candidate = tmux_session_name(&self.id, n);
                    let exists = std::process::Command::new("tmux")
                        .args(["-L", &tmux_socket(), "has-session", "-t", &candidate])
                        .output()
                        .is_ok_and(|o| o.status.success());
                    if !exists {
                        break candidate;
                    }
                    n += 1;
                }
            });
            let conf = state_dir.join("tmux.conf");
            std::fs::write(&conf, TMUX_CONF)?;
            // Create the session detached (synchronously) and only then attach:
            // the session never depends on the attaching client's timing.
            let exists = std::process::Command::new("tmux")
                .args(["-L", &tmux_socket(), "has-session", "-t", &name])
                .output()
                .is_ok_and(|o| o.status.success());
            if !exists {
                let mut create = std::process::Command::new("tmux");
                create
                    .args(["-L", &tmux_socket(), "-f"])
                    .arg(&conf)
                    .args([
                        "new-session",
                        "-d",
                        "-s",
                        &name,
                        "-x",
                        "80",
                        "-y",
                        "24",
                        "-c",
                    ])
                    .arg(&cwd);
                for (k, v) in &env {
                    create.arg("-e").arg(format!("{k}={v}"));
                }
                create.arg(&config.shell.program).args(&launch.args);
                let out = create.output()?;
                if !out.status.success() {
                    anyhow::bail!(
                        "tmux new-session failed: {}",
                        String::from_utf8_lossy(&out.stderr).trim()
                    );
                }
            }
            let args = vec![
                "-L".to_owned(),
                tmux_socket(),
                "attach-session".to_owned(),
                "-t".to_owned(),
                name.clone(),
            ];
            ("tmux".to_owned(), args, Some(name))
        } else {
            (config.shell.program.clone(), launch.args, None)
        };
        let opts = SpawnOptions {
            program,
            args,
            cwd,
            env,
            rows: 24,
            cols: 80,
            scrollback: config.scrollback_lines,
            label,
        };
        let session = PtySession::spawn(id, &opts, move |e| events.send(AppEvent::Pty(e)))?;
        self.next_number += 1;
        self.shells.push(Shell {
            session,
            number,
            tmux,
        });
        self.selected_shell = self.shells.len() - 1;
        self.show_shell = true;
        self.focus = Focus::Terminal;
        Ok(())
    }

    /// Bring the highlight cache up to date with the open document.
    pub fn refresh_highlight(&mut self) {
        let Some(ed) = &self.editor else {
            self.highlight = None;
            return;
        };
        let up_to_date = self
            .highlight
            .as_ref()
            .is_some_and(|h| h.path == ed.path() && h.revision == ed.revision());
        if up_to_date {
            return;
        }
        let language = match &self.highlight {
            Some(h) if h.path == ed.path() => Some(h.language),
            _ => Language::detect(ed.path(), ed.lines().first().map_or("", String::as_str)),
        };
        self.highlight = language.map(|language| HighlightCache {
            path: ed.path().to_path_buf(),
            revision: ed.revision(),
            language,
            states: language.line_states(ed.lines()),
        });
    }

    /// Whether the terminal pane should be drawn.
    pub fn shell_pane_visible(&self) -> bool {
        self.show_shell && !self.shells.is_empty()
    }

    /// The selected shell.
    pub fn active_shell(&self) -> Option<&Shell> {
        self.shells.get(self.selected_shell)
    }

    /// The selected shell, mutably.
    pub fn active_shell_mut(&mut self) -> Option<&mut Shell> {
        self.shells.get_mut(self.selected_shell)
    }

    /// Find a shell by id.
    pub fn shell_mut(&mut self, id: ShellId) -> Option<&mut Shell> {
        self.shells.iter_mut().find(|s| s.session.id() == id)
    }

    /// Move the shell selection by `delta`, clamped.
    pub fn select_shell(&mut self, delta: i32) {
        if self.shells.is_empty() {
            self.selected_shell = 0;
            return;
        }
        let max = self.shells.len() as i64 - 1;
        self.selected_shell =
            (self.selected_shell as i64 + i64::from(delta)).clamp(0, max) as usize;
    }

    /// Select shell number `index` (0-based) and focus the terminal. Returns `false` if absent.
    pub fn focus_shell(&mut self, index: usize) -> bool {
        if index >= self.shells.len() {
            return false;
        }
        self.selected_shell = index;
        self.show_shell = true;
        self.focus = Focus::Terminal;
        true
    }

    /// Kill and drop the selected shell.
    pub fn remove_active_shell(&mut self) {
        if self.selected_shell < self.shells.len() {
            let shell = self.shells.remove(self.selected_shell);
            // Stop the client first so it cannot recreate the session.
            let tmux = shell.tmux.clone();
            drop(shell);
            if let Some(name) = tmux {
                kill_tmux_session(&name);
            }
            self.selected_shell = self.selected_shell.min(self.shells.len().saturating_sub(1));
        }
    }

    /// Kill and drop the shell with `id`.
    pub fn remove_shell(&mut self, id: ShellId) {
        if let Some(i) = self.shells.iter().position(|s| s.session.id() == id) {
            let shell = self.shells.remove(i);
            // Stop the client first so it cannot recreate the session.
            let tmux = shell.tmux.clone();
            drop(shell);
            if let Some(name) = tmux {
                kill_tmux_session(&name);
            }
            self.selected_shell = self.selected_shell.min(self.shells.len().saturating_sub(1));
        }
    }

    /// Detach every tmux-backed shell so its session survives the drop.
    pub fn detach_tmux(&self) {
        for name in self.shells.iter().filter_map(|s| s.tmux.as_deref()) {
            detach_tmux_session(name);
        }
    }

    /// Kill every tmux session of this task's shells.
    pub fn kill_tmux(&self) {
        for name in self.shells.iter().filter_map(|s| s.tmux.as_deref()) {
            kill_tmux_session(name);
        }
    }

    /// Number of shells whose process is still running.
    pub fn live_shells(&self) -> usize {
        self.shells
            .iter()
            .filter(|s| !s.session.has_exited())
            .count()
    }

    /// Panes that can currently take focus, in cycling order.
    pub fn focus_order(&self) -> Vec<Focus> {
        let mut order = vec![Focus::Tree];
        if self.editor.is_some() {
            order.push(Focus::Editor);
        }
        order.push(Focus::Shells);
        if self.shell_pane_visible() {
            order.push(Focus::Terminal);
        }
        order
    }

    /// Focus the next (or previous) visible pane.
    pub fn cycle_focus(&mut self, forward: bool) {
        let order = self.focus_order();
        let idx = order.iter().position(|f| *f == self.focus).unwrap_or(0);
        let next = if forward {
            (idx + 1) % order.len()
        } else {
            (idx + order.len() - 1) % order.len()
        };
        self.focus = order[next];
        if self.focus != Focus::Terminal {
            self.zoomed = false;
        }
    }

    /// Focus a pane if it is available.
    pub fn set_focus(&mut self, focus: Focus) {
        if self.focus_order().contains(&focus) {
            self.focus = focus;
            if focus != Focus::Terminal {
                self.zoomed = false;
            }
        }
    }

    /// One-line summary of attachments for the sidebar.
    pub fn attachment_summary(&self) -> String {
        let mut parts = Vec::new();
        if !self.meta.workspaces.is_empty() {
            parts.push(format!("code: {}", self.meta.workspaces.join(", ")));
        }
        if !self.meta.builds.is_empty() {
            parts.push(format!("build: {}", self.meta.builds.join(", ")));
        }
        if let Some(b) = &self.meta.branch {
            parts.push(format!("branch: {b}"));
        }
        if !self.meta.gerrit.is_empty() {
            parts.push(format!("gerrit: {}", self.meta.gerrit.len()));
        }
        parts.join(" · ")
    }

    /// One-line plan status: context readiness and the next checkpoint.
    pub fn plan_summary(&self) -> String {
        let ready = if self.meta.context_ready {
            "context ready"
        } else {
            "context not ready"
        };
        match checkpoints::next_open(&self.checkpoints) {
            Some(i) => format!(
                "▸ {} ({}) · {}",
                self.checkpoints[i].title,
                checkpoints::fmt_minutes(self.checkpoints[i].estimate_min),
                checkpoints::summary(&self.checkpoints)
            ),
            None if !self.checkpoints.is_empty() => {
                format!("all {} checkpoints done", self.checkpoints.len())
            }
            None => format!("{ready} · no checkpoints"),
        }
    }
}
